In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

# local imports
from effcn.layers import FCCaps, FCCaps2
from effcn.functions import margin_loss, margin_loss2

### Compare FFC Caps MM & MK

In [9]:
torch.manual_seed(0)
x = torch.rand((2,3,4))
print(x)

torch.manual_seed(0)
FFC = FCCaps(3,2,4,5)(x)
torch.manual_seed(0)
FFC2 = FCCaps2(3,2,4,5)(x)

print(FFC.size())
print(FFC2.size())

assert FFC.size() == FFC2.size()

print(FFC)
print(FFC2)

print(FFC - FFC2)


tensor([[[0.4963, 0.7682, 0.0885, 0.1320],
         [0.3074, 0.6341, 0.4901, 0.8964],
         [0.4556, 0.6323, 0.3489, 0.4017]],

        [[0.0223, 0.1689, 0.2939, 0.5185],
         [0.6977, 0.8000, 0.1610, 0.2823],
         [0.6816, 0.9152, 0.3971, 0.8742]]])
torch.Size([2, 2, 5])
torch.Size([2, 2, 5])
tensor([[[ 0.2840, -0.3308, -0.2251, -0.3185, -0.0937],
         [ 0.0430,  0.3812,  0.0396, -0.0419,  0.1419]],

        [[ 0.1673, -0.4075,  0.2380, -0.1363,  0.0483],
         [-0.2170,  0.3545,  0.1635,  0.3683,  0.0387]]],
       grad_fn=<MulBackward0>)
tensor([[[ 0.2840, -0.3308, -0.2251, -0.3185, -0.0937],
         [ 0.0430,  0.3812,  0.0396, -0.0419,  0.1419]],

        [[ 0.1673, -0.4075,  0.2380, -0.1363,  0.0483],
         [-0.2170,  0.3545,  0.1635,  0.3683,  0.0387]]],
       grad_fn=<MulBackward0>)
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], grad_fn=<SubBackward0>)


##### check

### Compare loss MM & MK

In [31]:
torch.manual_seed(0)
u = torch.rand((3,3,5))
y = torch.tensor([[0,1,0],
                  [1,0,0],
                  [0,0,1]])
print(u)
print(y)

m = margin_loss(u,y)
m2 = margin_loss2(u,y)

print(m)
print(m2)
print(m-m2)

tensor([[[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
         [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
         [0.3489, 0.4017, 0.0223, 0.1689, 0.2939]],

        [[0.5185, 0.6977, 0.8000, 0.1610, 0.2823],
         [0.6816, 0.9152, 0.3971, 0.8742, 0.4194],
         [0.5529, 0.9527, 0.0362, 0.1852, 0.3734]],

        [[0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423],
         [0.5263, 0.2437, 0.5846, 0.0332, 0.1387]]])
tensor([[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]])
tensor(1.1541)
tensor(1.1541)
tensor(0.)


##### check